[package]
name = "activematter-rust"
version = "0.1.0"
edition = "2021"
authors = ["Pedro Burgos", "Philip Mocz"]
license = "GPL-3.0"

[dependencies]
rand = "0.8.5"
rayon = "1.10"
ndarray = {version = "0.15.4", features = ["rayon"]}

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

